<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Berries.Core\Berries.Core.csproj" />
    <ProjectReference Include="..\Berries.FileSystem.Abstractions\Berries.FileSystem.Abstractions.csproj" />
    <ProjectReference Include="..\Berries.FileSystem.Windows\Berries.FileSystem.Windows.csproj" />
  </ItemGroup>
</Project>
